version: 2
updates:
  # Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    groups:
      tauri:
        patterns:
          - "tauri*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
