//! macOS-only behavior: accessory activation policy, the `esphome-desktop`
//! shell command, and the LaunchServices relaunch used after app updates.

use std::os::unix::process::CommandExt;
use std::path::PathBuf;
use std::process::{Command, Stdio};
use tauri::{ActivationPolicy, AppHandle};

pub fn init(app_handle: &AppHandle) {
    // Tray-only app with no windows: mark it as an accessory app so it
    // doesn't appear in the Dock or the Cmd+Tab switcher.
    if let Err(e) = app_handle.set_activation_policy(ActivationPolicy::Accessory) {
        tracing::warn!("Failed to set macOS activation policy to Accessory: {e}");
    }

    install_cli_command();
}

/// Candidate PATH directories for the `esphome-desktop` shell command,
/// most-preferred first. Both are on the default PATH (`/usr/local/bin`
/// via `/etc/paths`, `/opt/homebrew/bin` via Homebrew's shellenv) and are
/// typically admin-user writable on machines with Homebrew installed.
const CLI_COMMAND_DIRS: &[&str] = &["/opt/homebrew/bin", "/usr/local/bin"];

/// Name of the shell command; must match the binary name the CLI parses as.
const CLI_NAME: &str = "esphome-desktop";

/// Marker identifying a wrapper as ours, so refreshes never touch a
/// user's own script or binary that happens to share the name.
const CLI_MARKER: &str = "auto-generated by ESPHome Device Builder";

/// What [`try_install_command_in`] found in one candidate directory.
enum CommandOutcome {
    /// Wrote or refreshed the wrapper.
    Installed,
    /// A current wrapper for this binary is already in place.
    AlreadyInstalled,
    /// Something that isn't ours occupies the name; leave it alone.
    Foreign,
    /// Directory missing or not writable; try the next candidate.
    Unavailable,
}

/// Install (or refresh) the `esphome-desktop` shell command so the CLI
/// control channel works from a terminal without hunting down the bundle
/// path. The command is a tiny self-cleaning wrapper script rather than a
/// symlink: deleting a macOS app runs no uninstall hooks, so a symlink
/// would dangle forever, while the wrapper notices the app is gone on its
/// next use and removes itself. Runs on every launch, which rewrites the
/// wrapper after the app is moved or reinstalled. Best-effort: no admin
/// prompt — if no candidate directory is writable the app just runs
/// without a shell command. Skipped for non-bundled dev builds, whose
/// `target/` path would go stale.
fn install_cli_command() {
    let exe = match std::env::current_exe() {
        Ok(exe) => exe,
        Err(e) => {
            tracing::debug!(
                "Could not determine current executable; skipping CLI command install: {e}"
            );
            return;
        }
    };
    if app_bundle_path().is_none() {
        tracing::debug!("Not running from an .app bundle; skipping CLI command install");
        return;
    }
    let script = wrapper_script(&exe);
    for dir in CLI_COMMAND_DIRS {
        match try_install_command_in(std::path::Path::new(dir), &script) {
            Ok(CommandOutcome::Installed) => {
                tracing::info!("Installed shell command {dir}/{CLI_NAME}");
                return;
            }
            Ok(CommandOutcome::AlreadyInstalled) => return,
            Ok(CommandOutcome::Foreign) => {
                // Don't fight the user's setup, and don't install a
                // second command elsewhere that PATH order may shadow.
                tracing::info!(
                    "Not installing the {CLI_NAME} shell command: {dir}/{CLI_NAME} \
                     exists and is not this app's wrapper"
                );
                return;
            }
            Ok(CommandOutcome::Unavailable) => continue,
            Err(e) => {
                tracing::debug!("Could not install the CLI command in {dir}: {e}");
            }
        }
    }
    tracing::debug!("No writable PATH directory for the CLI command");
}

/// The wrapper script: exec the bundle binary, or self-delete when the
/// app has been uninstalled (the only cleanup opportunity macOS gives us).
fn wrapper_script(exe: &std::path::Path) -> String {
    format!(
        "#!/bin/sh\n\
         # {CLI_MARKER}; safe to delete\n\
         APP={app}\n\
         if [ ! -x \"$APP\" ]; then\n\
         \techo \"ESPHome Device Builder is not installed; removing this command.\" >&2\n\
         \trm -f -- \"$0\"\n\
         \texit 127\n\
         fi\n\
         exec \"$APP\" \"$@\"\n",
        app = sh_single_quote(exe)
    )
}

/// Single-quote a path for embedding in a shell script, so spaces or
/// metacharacters in the bundle path can't break or inject anything.
fn sh_single_quote(path: &std::path::Path) -> String {
    format!("'{}'", path.to_string_lossy().replace('\'', r"'\''"))
}

/// Try to place the wrapper in one directory.
///
/// Replaces only what is safely ours: a marker-bearing wrapper (rewritten
/// when its content is outdated) or a dangling symlink. A regular file
/// without the marker, or a live symlink (a user's own arrangement that
/// works), is treated as foreign and left untouched.
fn try_install_command_in(dir: &std::path::Path, script: &str) -> std::io::Result<CommandOutcome> {
    use std::os::unix::fs::PermissionsExt;

    if !dir.is_dir() {
        return Ok(CommandOutcome::Unavailable);
    }
    let path = dir.join(CLI_NAME);
    match std::fs::symlink_metadata(&path) {
        Ok(meta) if meta.file_type().is_symlink() => {
            if path.exists() {
                return Ok(CommandOutcome::Foreign);
            }
            // Dangling link: litter nothing can use; reclaim the name.
            std::fs::remove_file(&path)?;
        }
        Ok(meta) if meta.is_file() => match std::fs::read_to_string(&path) {
            Ok(existing) => {
                if !existing.contains(CLI_MARKER) {
                    return Ok(CommandOutcome::Foreign);
                }
                if existing == script {
                    return Ok(CommandOutcome::AlreadyInstalled);
                }
            }
            // Not valid UTF-8: it can't be our ASCII wrapper, so it is
            // genuinely someone else's file; leave it alone.
            Err(e) if e.kind() == std::io::ErrorKind::InvalidData => {
                return Ok(CommandOutcome::Foreign);
            }
            // A transient failure (permissions, EIO) on a file that may
            // well be ours: propagate so the caller logs it and tries the
            // next candidate dir, instead of misreporting it as foreign.
            Err(e) => return Err(e),
        },
        Ok(_) => return Ok(CommandOutcome::Foreign),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
        Err(e) => return Err(e),
    }
    // Write-then-rename so a shell exec'ing the command mid-refresh never
    // sees a truncated script. Unlike the final `path`, these dirs can be
    // group-writable (Homebrew's /usr/local/bin, /opt/homebrew/bin — see
    // the note on CLI_COMMAND_DIRS), so a *fixed* staging name would let a
    // co-admin pre-plant it as a symlink that a plain `write` +
    // path-`set_permissions` would follow to clobber or chmod an arbitrary
    // file the app can reach. Defeat that with an unpredictable per-process
    // name plus `create_new` (O_CREAT|O_EXCL), which refuses to open
    // anything already at the name — a symlink included — and by chmod'ing
    // the file descriptor rather than the path.
    use std::io::Write;
    use std::os::unix::fs::OpenOptionsExt;
    static TMP_SEQ: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);
    let seq = TMP_SEQ.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    let tmp = dir.join(format!(".{CLI_NAME}.{}.{seq}.tmp", std::process::id()));
    let write = std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o700)
        .open(&tmp)
        .and_then(|mut f| {
            f.write_all(script.as_bytes())?;
            // fchmod on the fd (no symlink follow), widen to the intended
            // 0o755 only after the content is in place.
            f.set_permissions(std::fs::Permissions::from_mode(0o755))
        })
        .and_then(|()| std::fs::rename(&tmp, &path));
    match write {
        Ok(()) => Ok(CommandOutcome::Installed),
        Err(e) if e.kind() == std::io::ErrorKind::PermissionDenied => {
            let _ = std::fs::remove_file(&tmp);
            Ok(CommandOutcome::Unavailable)
        }
        Err(e) => {
            let _ = std::fs::remove_file(&tmp);
            Err(e)
        }
    }
}

/// Resolve the `.app` bundle directory from the running executable
/// (`<name>.app/Contents/MacOS/<bin>` -> `<name>.app`).
fn app_bundle_path() -> Option<PathBuf> {
    let exe = std::env::current_exe().ok()?;
    // ancestors(): <bin>, MacOS, Contents, <name>.app
    let bundle = exe.ancestors().nth(3)?;
    if bundle.extension().and_then(|e| e.to_str()) == Some("app") {
        Some(bundle.to_path_buf())
    } else {
        None
    }
}

/// Spawn a detached watcher that waits for this process to exit, then
/// relaunches the app through LaunchServices (`open`). We wait first because
/// `tauri-plugin-single-instance` would make a second instance started while
/// we're still quitting forward-and-exit instead of taking over. Returns
/// `false` (so the caller falls back to `restart()`) when the bundle path
/// can't be resolved or the watcher can't be spawned.
pub fn spawn_launchservices_relaunch() -> bool {
    let Some(bundle) = app_bundle_path() else {
        tracing::warn!("Could not resolve .app bundle path; falling back to direct restart");
        return false;
    };
    // The watcher blocks reading its stdin, which is the read end of a pipe
    // whose write end this process holds. When we exit, the kernel closes
    // that write end, `cat` sees EOF, and the watcher relaunches — so it
    // unblocks exactly when we terminate, with no PID-reuse race and no poll
    // latency. The bundle path is an argv positional ($1) so the shell never
    // parses it (spaces/metacharacters can't break the relaunch or inject a
    // command). Own process group so the watcher outlives us cleanly and
    // isn't caught by any signal aimed at our group.
    let mut child = match Command::new("/bin/sh")
        .arg("-c")
        .arg(r#"cat >/dev/null; exec /usr/bin/open "$1""#)
        .arg("sh") // $0
        .arg(&bundle) // $1, a positional the shell never parses (also fine if non-UTF-8)
        .stdin(Stdio::piped())
        .process_group(0)
        .spawn()
    {
        Ok(child) => child,
        Err(e) => {
            tracing::warn!("Failed to spawn LaunchServices relaunch watcher: {e}");
            return false;
        }
    };
    // Intentionally leak the pipe's write end so it stays open until this
    // process actually exits; that EOF is what releases the watcher. If we
    // dropped it here the watcher would fire immediately, racing our own
    // still-running instance against single-instance.
    if let Some(stdin) = child.stdin.take() {
        std::mem::forget(stdin);
    }
    true
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::util::unique_temp_dir;
    use std::fs;
    use std::path::Path;

    fn bin_dir(dir: &Path) -> PathBuf {
        let bin = dir.join("bin");
        fs::create_dir_all(&bin).expect("bin dir");
        bin
    }

    #[test]
    fn installs_fresh_wrapper() {
        let dir = unique_temp_dir("fresh");
        let bin = bin_dir(&dir);
        let script = wrapper_script(Path::new(
            "/Applications/Some App.app/Contents/MacOS/esphome-desktop",
        ));

        assert!(matches!(
            try_install_command_in(&bin, &script),
            Ok(CommandOutcome::Installed)
        ));
        let path = bin.join(CLI_NAME);
        let written = fs::read_to_string(&path).expect("read wrapper");
        assert_eq!(written, script);
        assert!(written.starts_with("#!/bin/sh"));
        assert!(written.contains(CLI_MARKER));
        // The space-bearing path must be embedded quoted.
        assert!(written.contains("'/Applications/Some App.app/Contents/MacOS/esphome-desktop'"));
        use std::os::unix::fs::PermissionsExt;
        let mode = fs::metadata(&path).expect("meta").permissions().mode();
        assert_eq!(mode & 0o111, 0o111, "wrapper must be executable");

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn current_wrapper_is_a_noop() {
        let dir = unique_temp_dir("noop");
        let bin = bin_dir(&dir);
        let script = wrapper_script(Path::new(
            "/Applications/A.app/Contents/MacOS/esphome-desktop",
        ));
        assert!(matches!(
            try_install_command_in(&bin, &script),
            Ok(CommandOutcome::Installed)
        ));
        assert!(matches!(
            try_install_command_in(&bin, &script),
            Ok(CommandOutcome::AlreadyInstalled)
        ));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn outdated_wrapper_is_rewritten() {
        // The app moved: same marker, different baked path.
        let dir = unique_temp_dir("outdated");
        let bin = bin_dir(&dir);
        let old = wrapper_script(Path::new("/old/App.app/Contents/MacOS/esphome-desktop"));
        let new = wrapper_script(Path::new("/new/App.app/Contents/MacOS/esphome-desktop"));
        assert!(matches!(
            try_install_command_in(&bin, &old),
            Ok(CommandOutcome::Installed)
        ));

        assert!(matches!(
            try_install_command_in(&bin, &new),
            Ok(CommandOutcome::Installed)
        ));
        assert_eq!(fs::read_to_string(bin.join(CLI_NAME)).expect("read"), new);

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn foreign_file_is_left_alone() {
        let dir = unique_temp_dir("foreign_file");
        let bin = bin_dir(&dir);
        fs::write(bin.join(CLI_NAME), "someone else's binary").expect("foreign");
        let script = wrapper_script(Path::new(
            "/Applications/A.app/Contents/MacOS/esphome-desktop",
        ));

        assert!(matches!(
            try_install_command_in(&bin, &script),
            Ok(CommandOutcome::Foreign)
        ));
        assert_eq!(
            fs::read_to_string(bin.join(CLI_NAME)).expect("read"),
            "someone else's binary"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn non_utf8_file_is_left_alone() {
        // A real foreign binary is not valid UTF-8; it still can't be our
        // ASCII wrapper, so it must be treated as foreign and untouched.
        let dir = unique_temp_dir("non_utf8");
        let bin = bin_dir(&dir);
        let bytes = [0xffu8, 0xfe, 0x00];
        fs::write(bin.join(CLI_NAME), bytes).expect("foreign binary");
        let script = wrapper_script(Path::new(
            "/Applications/A.app/Contents/MacOS/esphome-desktop",
        ));

        assert!(matches!(
            try_install_command_in(&bin, &script),
            Ok(CommandOutcome::Foreign)
        ));
        assert_eq!(fs::read(bin.join(CLI_NAME)).expect("read"), bytes);

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn unreadable_wrapper_is_propagated_not_foreign() {
        // A transient read failure on a same-named file must propagate as an
        // error, not collapse to Foreign (which would abandon the remaining
        // candidate dirs on a misleading "not this app's wrapper" log).
        use std::os::unix::fs::PermissionsExt;
        let dir = unique_temp_dir("unreadable");
        let bin = bin_dir(&dir);
        let path = bin.join(CLI_NAME);
        fs::write(&path, "anything").expect("write");
        fs::set_permissions(&path, fs::Permissions::from_mode(0o000)).expect("chmod");
        let script = wrapper_script(Path::new(
            "/Applications/A.app/Contents/MacOS/esphome-desktop",
        ));

        // Root bypasses the mode bits, so the unreadable scenario can't be
        // exercised there; skip rather than fail.
        if fs::read_to_string(&path).is_ok() {
            let _ = fs::remove_dir_all(&dir);
            return;
        }

        assert!(try_install_command_in(&bin, &script).is_err());

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn live_symlink_is_left_alone() {
        // A user's own working symlink (e.g. straight to the bundle)
        // already does the job; don't replace it.
        let dir = unique_temp_dir("live_link");
        let bin = bin_dir(&dir);
        let other = dir.join("user-wrapper");
        fs::write(&other, "bin").expect("write target");
        std::os::unix::fs::symlink(&other, bin.join(CLI_NAME)).expect("preinstall");
        let script = wrapper_script(Path::new(
            "/Applications/A.app/Contents/MacOS/esphome-desktop",
        ));

        assert!(matches!(
            try_install_command_in(&bin, &script),
            Ok(CommandOutcome::Foreign)
        ));
        assert_eq!(fs::read_link(bin.join(CLI_NAME)).expect("link"), other);

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn dangling_symlink_is_replaced() {
        let dir = unique_temp_dir("dangling");
        let bin = bin_dir(&dir);
        std::os::unix::fs::symlink(dir.join("gone"), bin.join(CLI_NAME)).expect("preinstall");
        let script = wrapper_script(Path::new(
            "/Applications/A.app/Contents/MacOS/esphome-desktop",
        ));

        assert!(matches!(
            try_install_command_in(&bin, &script),
            Ok(CommandOutcome::Installed)
        ));
        assert_eq!(
            fs::read_to_string(bin.join(CLI_NAME)).expect("read"),
            script
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn staging_file_does_not_follow_a_planted_symlink() {
        // These PATH dirs can be group-writable, so a co-admin could try to
        // hijack the staging file: pre-plant the old fixed staging name as a
        // symlink to a file they want the app to clobber/chmod. The install
        // must not follow it — it stages under an unpredictable name.
        use std::os::unix::fs::PermissionsExt;
        let dir = unique_temp_dir("staging_symlink");
        let bin = bin_dir(&dir);
        let victim = dir.join("victim");
        fs::write(&victim, "untouched").expect("victim");
        let victim_mode_before = fs::metadata(&victim).expect("meta").permissions().mode();
        // The name a fixed-staging implementation would use.
        std::os::unix::fs::symlink(&victim, bin.join(format!(".{CLI_NAME}.tmp"))).expect("plant");
        let script = wrapper_script(Path::new(
            "/Applications/A.app/Contents/MacOS/esphome-desktop",
        ));

        assert!(matches!(
            try_install_command_in(&bin, &script),
            Ok(CommandOutcome::Installed)
        ));
        // The wrapper landed, and the planted symlink's target was never
        // written through nor chmod'd.
        assert_eq!(
            fs::read_to_string(bin.join(CLI_NAME)).expect("read"),
            script
        );
        assert_eq!(
            fs::read_to_string(&victim).expect("victim"),
            "untouched",
            "the staging write must not follow the planted symlink"
        );
        assert_eq!(
            fs::metadata(&victim).expect("meta").permissions().mode(),
            victim_mode_before,
            "the staging chmod must not follow the planted symlink"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn missing_directory_is_unavailable() {
        let dir = unique_temp_dir("missing_dir");
        let script = wrapper_script(Path::new(
            "/Applications/A.app/Contents/MacOS/esphome-desktop",
        ));

        assert!(matches!(
            try_install_command_in(&dir.join("no-such-bin"), &script),
            Ok(CommandOutcome::Unavailable)
        ));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn wrapper_execs_the_app_when_present() {
        // End to end through /bin/sh: the wrapper must exec the target
        // with its arguments forwarded.
        let dir = unique_temp_dir("exec");
        let bin = bin_dir(&dir);
        // A stand-in "app binary" that proves it ran with our args.
        let app = dir.join("fake app.bin");
        fs::write(&app, "#!/bin/sh\necho \"ran with: $1\"\n").expect("write app");
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&app, fs::Permissions::from_mode(0o755)).expect("chmod app");
        let script = wrapper_script(&app);
        assert!(matches!(
            try_install_command_in(&bin, &script),
            Ok(CommandOutcome::Installed)
        ));

        let output = std::process::Command::new(bin.join(CLI_NAME))
            .arg("status")
            .output()
            .expect("run wrapper");
        assert!(output.status.success());
        assert_eq!(
            String::from_utf8_lossy(&output.stdout),
            "ran with: status\n"
        );
        assert!(bin.join(CLI_NAME).exists(), "wrapper must survive success");

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn wrapper_self_deletes_when_the_app_is_gone() {
        // The uninstall case: app path missing → explain, remove itself,
        // exit 127.
        let dir = unique_temp_dir("self_delete");
        let bin = bin_dir(&dir);
        let script = wrapper_script(&dir.join("Trashed.app/Contents/MacOS/esphome-desktop"));
        assert!(matches!(
            try_install_command_in(&bin, &script),
            Ok(CommandOutcome::Installed)
        ));

        let output = std::process::Command::new(bin.join(CLI_NAME))
            .output()
            .expect("run wrapper");
        assert_eq!(output.status.code(), Some(127));
        assert!(String::from_utf8_lossy(&output.stderr).contains("not installed"));
        assert!(
            !bin.join(CLI_NAME).exists(),
            "wrapper must remove itself once the app is gone"
        );

        let _ = fs::remove_dir_all(&dir);
    }
}
