#!/usr/bin/env python3
"""Record everything that ships with a Python interpreter itself (#330).

Run *by the interpreter being recorded*, with its tree root as the only
argument; prints the manifest to stdout::

    "$python_dir/$python_bin" write_base_manifest.py "$python_dir" \
        > "$python_dir/.base-packages"

The app repairs a broken bundled tree by deleting the packages it installed and
reinstalling them. That only works if it can tell its packages apart from
Python's own, and nothing on disk distinguishes them: pip, esphome and every
dependency sit side by side in site-packages, and pip's own metadata is exactly
what is unreliable in the trees that need repairing. So the answer is captured
at build time, at the one moment it is knowable for certain -- after pip is
upgraded and before anything of ours is installed on top -- and shipped inside
the tree.

The directory layout comes from sysconfig rather than being spelled out, because
it is platform-specific (``lib/pythonX.Y/site-packages`` + ``bin`` against
``Lib\\site-packages`` + ``Scripts``). Paths are recorded relative to the tree
root, so the reset needs no knowledge of either layout and the manifest survives
the copy into the user's data directory on macOS and Linux.

Consumed by ``wipe_installed_packages`` in src-tauri/src/platform/mod.rs; the
format is pinned from the Rust side by ``parse_base_manifest``'s tests and from
this side by tests/test_write_base_manifest.py.
"""

from __future__ import annotations

import sys
import sysconfig
from pathlib import Path

# Directories the reset cleans out. `purelib` is site-packages; `scripts` is
# `bin` (or `Scripts` on Windows), which holds pip-installed entry points such
# as `esphome` and `esptool` alongside Python's own `python3` and `pip3`.
SWEPT_PATHS = ("purelib", "scripts")

HEADER = """\
# Everything that ships with the interpreter itself.
# Generated by build-scripts/write_base_manifest.py; do not edit by hand.
#
# `sweep` marks a directory the app's package reset cleans out; `keep` marks an
# entry inside one that belongs to Python rather than to us, and so must
# survive. Paths are relative to the Python tree root, POSIX separators on every
# platform.
#
# `keep` names the exact version that shipped, but the reset matches
# `<name>-<version>.dist-info` on the distribution name alone: a base package
# whose version moves after this snapshot (pip upgrading itself, say) must still
# be recognised as Python's, or the reset would delete its metadata and leave it
# with no RECORD -- the very state the reset exists to repair."""


def build_manifest(root: Path) -> str:
    """Return the manifest text for the tree rooted at `root`.

    `root` must be the tree of the *running* interpreter, since the directories
    are read from its sysconfig.
    """
    swept: list[tuple[Path, Path]] = []
    for key in SWEPT_PATHS:
        path = Path(sysconfig.get_path(key)).resolve()
        try:
            rel = path.relative_to(root)
        except ValueError:
            raise SystemExit(
                f"{key} ({path}) is outside the Python tree ({root}); "
                "the manifest must be generated by the interpreter it describes"
            ) from None
        swept.append((rel, path))

    kept: list[Path] = []
    for rel, path in swept:
        # A swept directory that does not exist would be recorded with nothing
        # to keep inside it, and the reset would then clean it out entirely --
        # which for site-packages means deleting the interpreter's own pip, the
        # one thing no repair can come back from. Both directories exist at the
        # point prepare_bundle.sh calls this, so getting here means something
        # about the tree is not what we think, and guessing is not an option.
        if not path.is_dir():
            raise SystemExit(f"{rel.as_posix()} ({path}) is not a directory")
        children = sorted(path.iterdir())
        if not children:
            raise SystemExit(f"{rel.as_posix()} ({path}) is empty")
        kept += [rel / child.name for child in children]

    # The manifest is only useful if it spares pip, since the repair reinstalls
    # with it. Assert it here, where the artifact is produced and a failure stops
    # the build, rather than on a user's machine at the moment their repair is
    # refused. Checked against the paths themselves rather than the rendered
    # text, so a change to the format cannot quietly stop the check matching.
    if not any(k.name == "pip" for k in kept):
        raise SystemExit("manifest does not name pip; refusing to write it")

    lines = [HEADER]
    lines += [f"sweep {rel.as_posix()}" for rel, _ in swept]
    lines += [f"keep {k.as_posix()}" for k in kept]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    if len(argv) != 1:
        print(f"usage: {Path(__file__).name} <python_dir>", file=sys.stderr)
        return 2
    print(build_manifest(Path(argv[0]).resolve()))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
