name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  release-drafter:
    runs-on: ubuntu-latest
    environment: release-drafter
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          app-id: ${{ secrets.ESPHOME_GITHUB_APP_ID }}
          private-key: ${{ secrets.ESPHOME_GITHUB_APP_PRIVATE_KEY }}

      - uses: release-drafter/release-drafter@5de93583980a40bd78603b6dfdcda5b4df377b32 # v7.2.0
        id: release-draft
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      # Update version numbers in Cargo.toml and tauri.conf.json
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Calculate version
        id: version
        run: |
          tag="${{ steps.release-draft.outputs.tag_name }}"
          echo "version=${tag:1}" >> $GITHUB_OUTPUT

      - name: Set Cargo.toml version
        run: |
          sed -i "s/^version = .*/version = \"${{ steps.version.outputs.version }}\"/g" src-tauri/Cargo.toml

      - name: Set tauri.conf.json version
        run: |
          sed -i "s/\"version\": .*/\"version\": \"${{ steps.version.outputs.version }}\",/g" src-tauri/tauri.conf.json

      - name: Set PKGBUILD versions
        run: |
          sed -i "s/^pkgver=.*/pkgver=${{ steps.version.outputs.version }}/g" packaging/aur/esphome-desktop-bin/PKGBUILD

      - name: Update Cargo.lock
        run: |
          cd src-tauri
          cargo update --workspace

      # github actions email from here: https://github.community/t/github-actions-bot-email-address/17204
      - name: Commit changes
        run: |
          if ! git diff --quiet; then
            git config --global user.name "esphomebot"
            git config --global user.email "68923041+esphomebot@users.noreply.github.com"
            git commit -am "Bump version to ${{ steps.version.outputs.version }}"
            git push
          fi
